[
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "<!channel>: just so nobody misses it, since we've just merged in user table changes, the user table is going to get rewritten",
        "ts": "1454274033.000047"
    },
    {
        "type": "message",
        "user": "U0HUH2B1R",
        "text": "<@U0J0D1KE3>: Are you guys rewritting the user table or is that a task that\u2019s up for grabs? P.s. I\u2019m so used to typing out your handle as stevar.",
        "ts": "1454274403.000048"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "umm <@U0J0A2MTL> can you answer this, i just wanted to make sure nobody gets alarmed when the table has different content than they remembered",
        "ts": "1454274517.000049"
    },
    {
        "type": "message",
        "user": "U0J0A2MTL",
        "text": "If we run the UserConnection.sync({force: true}), all the tables will be erased, with new columns in the user table.  If you are talking about the mockaroo thing, generating new fake users with more data is 'up for grabs'.",
        "ts": "1454274698.000050"
    },
    {
        "type": "message",
        "user": "U0HUH2B1R",
        "text": "Awesome.",
        "ts": "1454274746.000051"
    },
    {
        "type": "message",
        "user": "U0HUH2B1R",
        "text": "Thanks guys",
        "ts": "1454274751.000052"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "soooo.... i tried merging with mainline and idk how to make these DB errors go away...",
        "ts": "1454279116.000053"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "anyone know how to fix this???\nUnhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: users\n    at Query.formatError (\/home\/steve\/Gradr\/code\/server\/node_modules\/sequelize\/lib\/dialects\/sqlite\/query.js:348:14)\n    at afterExecute (\/home\/steve\/Gradr\/code\/server\/node_modules\/sequelize\/lib\/dialects\/sqlite\/query.js:112:29)\n    at Statement.errBack (\/home\/steve\/Gradr\/code\/server\/node_modules\/sqlite3\/lib\/sqlite3.js:16:21)\n\nUnhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: users\n    at Query.formatError (\/home\/steve\/Gradr\/code\/server\/node_modules\/sequelize\/lib\/dialects\/sqlite\/query.js:348:14)\n    at afterExecute (\/home\/steve\/Gradr\/code\/server\/node_modules\/sequelize\/lib\/dialects\/sqlite\/query.js:112:29)\n    at Statement.errBack (\/home\/steve\/Gradr\/code\/server\/node_modules\/sqlite3\/lib\/sqlite3.js:16:21)",
        "edited": {
            "user": "U0J0D1KE3",
            "ts": "1454279276.000000"
        },
        "ts": "1454279261.000054"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "this is now that i just deleted the sqlite db because it was giving me even more problems",
        "ts": "1454279297.000056"
    },
    {
        "type": "message",
        "user": "U0J0A2MTL",
        "text": "Have you gone into Users.js and uncommented line 46?",
        "ts": "1454279359.000057"
    },
    {
        "type": "message",
        "user": "U0J0A2MTL",
        "text": "If not, try running the server once with that line uncommented, then comment it again and see if it works.",
        "ts": "1454279400.000058"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "ok that worked",
        "ts": "1454279429.000059"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "i did try it, but it didn't work so i commented it again",
        "ts": "1454279441.000060"
    },
    {
        "type": "message",
        "user": "U0J0D1KE3",
        "text": "but looks like when i deleted my old sqlite file, and then brought in the one in iteration1, it worked",
        "ts": "1454279481.000061"
    }
]